create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check (char_length(trim(nickname)) between 2 and 30),
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  description text not null,
  author_id uuid not null,
  created_at timestamptz not null default now(),
  constraint feedback_author_id_fkey
    foreign key (author_id) references public.profiles(id) on delete cascade
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'feedback'
      and column_name = 'title'
  ) then
    execute 'update public.feedback set description = title where trim(description) = ''''';
    execute 'alter table public.feedback drop column title';
  end if;
end
$$;

alter table public.feedback alter column description drop default;
alter table public.feedback drop constraint if exists feedback_description_check;
alter table public.feedback drop constraint if exists feedback_description_length_check;
alter table public.feedback
add constraint feedback_description_length_check
check (char_length(trim(description)) between 3 and 600);

create table if not exists public.votes (
  feedback_id bigint not null references public.feedback(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (feedback_id, user_id)
);

create index if not exists idx_feedback_created_at
on public.feedback(created_at desc);

alter table public.profiles enable row level security;
alter table public.feedback enable row level security;
alter table public.votes enable row level security;

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "Users can create their own profile" on public.profiles;
create policy "Users can create their own profile"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "Authenticated users can read feedback" on public.feedback;
create policy "Authenticated users can read feedback"
on public.feedback for select
to authenticated
using (true);

drop policy if exists "Users can create their own feedback" on public.feedback;
create policy "Users can create their own feedback"
on public.feedback for insert
to authenticated
with check ((select auth.uid()) = author_id);

drop policy if exists "Authenticated users can read votes" on public.votes;
create policy "Authenticated users can read votes"
on public.votes for select
to authenticated
using (true);

drop policy if exists "Users can add their own vote" on public.votes;
create policy "Users can add their own vote"
on public.votes for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can remove their own vote" on public.votes;
create policy "Users can remove their own vote"
on public.votes for delete
to authenticated
using ((select auth.uid()) = user_id);

grant usage on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.feedback to authenticated;
grant select, insert, delete on public.votes to authenticated;
grant usage, select on sequence public.feedback_id_seq to authenticated;

analyze public.feedback;
analyze public.votes;
